version: '2'
services:
  drone-server:
    image: drone/drone:1.0.0-rc.5
    ports:
      - "8081:80"
      - 9000
    volumes:
      - ./drone:/var/lib/drone/
    environment:
      - DRONE_OPEN=true
      - DRONE_SERVER_HOST=drone-server
      - DRONE_GITHUB_SERVER=https://github.com
      - DRONE_GITHUB_CLIENT_ID=6b536fc72a9ada749c54
      - DRONE_GITHUB_CLIENT_SECRET=3be987aa5dbebfb7086959a8a55e9d2778114a75
      - DRONE_DEBUG=true
      - DRONE_GITHUB=true
      - DRONE_PROVIDER=github
      - DRONE_RPC_SECRET=ALQU2M0KdptXUdTPKcEw
  drone-agent:
    image: drone/agent:1.0.0-rc.5
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_SERVER=drone-server:9000
      - DRONE_RPC_SECRET=ALQU2M0KdptXUdTPKcEw
      - DRONE_DEBUG=true
